### ISSUE TITLE
Bug: Navbar Icon + text  hovering property not working properly.

### ISSUE THREAD

**Issue by yagyaraj234** [oyepriyansh/DevTweet#93] opened 2023-10-03 16:31 UTC
### Description

The Navbar route hovering property not working properly.

When the user hovers over the name of the route the hover property works properly on both icon + aligned text. 
But when the user only hovers on the icon the hover property is not applied to the aligned text

### Screenshots

**Screenshots :**

![Screenshot (87)](https://github.com/oyepriyansh/DevTweet/assets/101352591/e880a5f6-6e5f-45c8-8cd2-430eefa097ee)
![Screenshot (86)](https://github.com/oyepriyansh/DevTweet/assets/101352591/2f375c5c-6897-4273-8b48-85d8f8881119)

### What browsers are you seeing the problem on?

Chrome

### Ready to Work?

- [X] I want to work on this issue

**Comment by ritik48** [comment] 2023-10-03 16:38
@oyepriyansh please assign this issue to me

**Comment by oyepriyansh** [comment] 2023-10-03 16:39
Duplicate of #25

**Comment by yagyaraj234** [comment] 2023-10-03 17:02
Okay so can I fix this issue

**Comment by oyepriyansh** [comment] 2023-10-03 17:09
@techmannih is already working on that issue, if he is not able to do it then i will assign it to you

**Comment by yagyaraj234** [comment] 2023-10-03 17:13
Actually, I have fixed the issue. Whenever you assign me I will make a pull request.

**Comment by techmannih** [comment] 2023-10-04 02:04
hello @yagyaraj234 , you can't create PR without  assign you. this issue  have assigned me then I will create

**Comment by techmannih** [comment] 2023-10-04 02:12
please create another issue and work on it

**Comment by yagyaraj234** [comment] 2023-10-04 06:37
Hi, @techmannih 
I am not creating any PR if you are not able to fix the issue inform me then I will create it.

**Closed** 2023-10-04 16:17 UTC
Labels: bug, duplicate
