### ISSUE TITLE
Bug: change Github icon 

### ISSUE THREAD

**Issue by techmannih** [oyepriyansh/DevTweet#138] opened 2023-10-08 02:14 UTC
### Description

Hello @oyepriyansh ,
I found an issue in your website in which githib icon is invalid and 
I want to work on this issue please assign me

### Screenshots

![Screenshot_20231008_074146_Chrome](https://github.com/oyepriyansh/DevTweet/assets/125847751/32c37532-796b-4347-b82f-3c44b26e0ef4)

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment] 2023-10-08 06:10
duplicate of #99

**Closed** 2023-10-08 09:01 UTC
Labels: bug, duplicate

**Comment by techmannih** [comment] 2023-10-08 20:03
Hello @oyepriyansh 
This issue not solve yet and he has also closed this issue without solving or any pull request 
So I want to solve this issue can you assign me this issue

**Comment by WilliamDavidHarrison** [comment] 2023-10-09 00:54
@techmannih This is a duplicate issue of #99 as Priyansh said, you will not be assigned to work on it.
